# Generated by Django 3.1.3 on 2020-12-05 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='job_type',
            field=models.CharField(choices=[('Full time', 'Full time'), ('part time', 'part time')], default='', max_length=15),
            preserve_default=False,
        ),
    ]
