# Generated by Django 3.1.3 on 2020-12-05 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_home_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='Description',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
