# Generated by Django 3.1.3 on 2020-12-05 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_home_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='home',
            name='published_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='home',
            name='salary',
            field=models.IntegerField(default=0),
        ),
    ]
