# Generated by Django 3.1.3 on 2020-12-07 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20201205_1808'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='home',
            new_name='homei',
        ),
    ]
