# Generated by Django 3.1.3 on 2020-12-07 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20201208_0058'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='homei',
            new_name='home',
        ),
    ]
